using CupriFace;
using CupriFace.Binding;
using CupriFace.Resources;
using SkiaSharp;

namespace CupriFace.Demo;

/// <summary>
/// One app that shows everything: a tabbed showcase of the control set, overlays, layout
/// (flex + grid), and motion — plus live binding, navigation, and interaction. A portable
/// <see cref="CupriApp"/>, so the desktop Viewer and the web hosts run the identical demo.
/// </summary>
public sealed class ShowcaseApp : CupriApp
{
    private readonly ShowcaseModel _model = new();

    public override string Title => "CupriFace — Showcase";
    public override int Width => 940;
    public override int Height => 720;
    public override SKColor Background => _model.DarkMode ? new SKColor(0x0f, 0x14, 0x20) : new SKColor(0xf4, 0xf5, 0xf7);
    public override object Model => _model;
    // Only re-bind live while the Diagnostics readout is visible — a full rebuild every second
    // on every tab is wasted work (and a visible hitch on the CPU-rendered web host).
    public override double RefreshIntervalSeconds => _model.Section == "diag" ? 1.0 : 0;

    // Markup and styles live in editable files under Assets/ and are embedded at compile time.
    // `Assets` is generated by CupriFace.Resources.Gen — a renamed/missing file is a compile error.
    protected override CupriSource MarkupSource => Assets.ShowcaseApp.Html;
    protected override CupriSource StyleSource => Assets.ShowcaseApp.Css;

    public override void Configure(CupriDocument doc)
    {
        doc.OnClick(".nav", e => { if (e.Element.GetAttribute("data-section") is { } s) _model.Section = s; });
        doc.OnClick(".act-dialog", _ => _model.DialogOpen = true);
        doc.OnClick(".act-drawer", _ => _model.DrawerOpen = true);
        doc.OnClick(".act-toast", _ => _model.ShowToast = !_model.ShowToast);
        doc.OnClick(".act-gc", _ => GC.Collect());
        // Zoom via buttons — a slider would fight the live re-scale it triggers.
        doc.OnClick(".zoom-dec", _ => _model.ZoomPct = Math.Clamp(_model.ZoomPct - 10, 80, 200));
        doc.OnClick(".zoom-inc", _ => _model.ZoomPct = Math.Clamp(_model.ZoomPct + 10, 80, 200));
    }

    public override PresentInfo Present(float w, float h) => _model.Scaling switch
    {
        "none" => new PresentInfo(Width, Height, 1f),                                  // fixed design size
        "zoom" => Zoomed(w, h, _model.ZoomPct / 100f),                                 // hard DPI-like scale
        "hybrid" => Zoomed(w, h, MathF.Min(w / Width, h / Height)),                    // fit the tighter axis, reflow the other
        _ => new PresentInfo(w, h, 1f),                                                // responsive
    };

    private static PresentInfo Zoomed(float w, float h, float z)
    {
        z = Math.Clamp(z, 0.25f, 4f);
        return new PresentInfo(w / z, h / z, z);
    }
}

[CupriBindable]
public sealed partial class ShowcaseModel
{
    public string Section { get; set; } = "controls";

    public string SecControls => Section == "controls" ? "block" : "none";
    public string SecComponents => Section == "components" ? "block" : "none";
    public string SecImages => Section == "images" ? "block" : "none";
    public string SecOverlays => Section == "overlays" ? "block" : "none";
    public string SecLayout => Section == "layout" ? "block" : "none";
    public string SecMotion => Section == "motion" ? "block" : "none";
    public string SecSettings => Section == "settings" ? "block" : "none";
    public string SecDiag => Section == "diag" ? "block" : "none";
    public string NavControls => Section == "controls" ? "active" : "";
    public string NavComponents => Section == "components" ? "active" : "";
    public string NavImages => Section == "images" ? "active" : "";
    public string NavOverlays => Section == "overlays" ? "active" : "";
    public string NavLayout => Section == "layout" ? "active" : "";
    public string NavMotion => Section == "motion" ? "active" : "";
    public string NavSettings => Section == "settings" ? "active" : "";
    public string NavDiag => Section == "diag" ? "active" : "";

    public string Scaling { get; set; } = "hybrid";
    public int ZoomPct { get; set; } = 100;
    public string ThemeClass => DarkMode ? "dark" : "";

    public int Volume { get; set; } = 60;
    public string Name { get; set; } = "";
    public int Quantity { get; set; } = 3;
    public bool Notifications { get; set; } = true;
    public bool DarkMode { get; set; }
    public string Size { get; set; } = "medium";
    public string ImageFit { get; set; } = "contain"; // <cupri-image> object-fit, chosen via radios
    public bool DialogOpen { get; set; }
    public bool DrawerOpen { get; set; }
    public bool MenuOpen { get; set; }
    public bool ShowToast { get; set; }
    public string ToastDisplay => ShowToast ? "block" : "none";

    // Components section
    public string Tab { get; set; } = "one";
    public bool SizeOpen { get; set; }
    public string Notes { get; set; } = "";
    public bool Acc1 { get; set; } = true;
    public bool Acc2 { get; set; }
    public bool TreeOpen { get; set; } = true;
    public bool PopOpen { get; set; }

    // Diagnostics — live metrics. The OS-process metrics (working set, private bytes, threads)
    // are EXPENSIVE (Process.GetCurrentProcess + Threads enumerates every thread) and would run
    // on every data-bind (i.e. every click/keystroke, even when the tab is hidden), so they're
    // sampled at most once per second into a cache. GC/Stopwatch are cheap. On the browser WASM
    // sandbox System.Diagnostics.Process is unsupported → the process metrics show "n/a".
    private static readonly System.Diagnostics.Stopwatch _up = System.Diagnostics.Stopwatch.StartNew();
    private static string Mb(long bytes) => (bytes / (1024.0 * 1024)).ToString("0.0") + " MB";
    private static double _lastSample = -1;
    private static string _ws = "…", _pv = "…", _thr = "…";
    private static void Sample()
    {
        var now = _up.Elapsed.TotalSeconds;
        if (now - _lastSample < 1.0) return; // cache: at most once per second
        _lastSample = now;
        try { using var p = System.Diagnostics.Process.GetCurrentProcess(); _ws = Mb(p.WorkingSet64); _pv = Mb(p.PrivateMemorySize64); _thr = p.Threads.Count.ToString(); }
        catch { _ws = _pv = _thr = "n/a"; } // browser/WASM — Process is unsupported
    }
    public string WorkingSetMb { get { Sample(); return _ws; } }
    public string PrivateMb { get { Sample(); return _pv; } }
    public string Threads { get { Sample(); return _thr; } }
    public string ManagedHeapMb => Mb(GC.GetTotalMemory(false));
    public string GcCounts => $"{GC.CollectionCount(0)} / {GC.CollectionCount(1)} / {GC.CollectionCount(2)}";
    public string Uptime => $"{(int)_up.Elapsed.TotalMinutes}m {_up.Elapsed.Seconds:00}s";
}
