using CupriFace;
using CupriFace.Binding;
using CupriFace.Paint;
using CupriFace.Resources;
using SkiaSharp;

namespace CupriFace.Demo;

/// <summary>
/// One app that shows everything: a tabbed showcase of the control set, overlays, layout
/// (flex + grid), and motion — plus live binding, navigation, and interaction. A portable
/// <see cref="CupriApp"/>, so the desktop Viewer and the web hosts run the identical demo.
/// </summary>
public sealed class ShowcaseApp : CupriApp
{
    private readonly ShowcaseModel _model = new();

    // Section ids a <a href="…"> link may route to (mirrors the sidebar nav). An unknown internal href
    // is ignored rather than blanking every section.
    private static readonly HashSet<string> KnownSections =
        ["controls", "components", "charts", "images", "3d", "overlays", "layout", "motion", "styling",
         "keyboard", "settings", "diag"];

    /// <summary>Optionally start on a given section (a sidebar id like "images") — the hosts pass
    /// e.g. `--section images` through, so a dev (or a UI test) lands straight on the page under
    /// work. Unknown ids keep the default.</summary>
    public ShowcaseApp(string? section = null)
    {
        if (section is not null && KnownSections.Contains(section)) _model.Section = section;
    }

    public override string Title => "CupriFace — Showcase";
    public override byte[] Icon => EmbeddedAsset("Assets/logo-512.png").ReadBytes();
    public override int Width => 940;
    public override int Height => 720;
    public override SKColor Background => _model.DarkMode ? new SKColor(0x0f, 0x14, 0x20) : new SKColor(0xf4, 0xf5, 0xf7);
    public override object Model => _model;
    // Only re-bind live while the Diagnostics readout is visible — a full rebuild every second
    // on every tab is wasted work (and a visible hitch on the CPU-rendered web host).
    public override double RefreshIntervalSeconds => _model.Section == "diag" ? 1.0 : 0;

    // Markup and styles live in editable files under Assets/ and are embedded at compile time.
    // `Assets` is generated by CupriFace.Resources.Gen — a renamed/missing file is a compile error.
    protected override CupriSource MarkupSource => Assets.ShowcaseApp.Html;
    protected override CupriSource StyleSource => Assets.ShowcaseApp.Css;

    public override void Configure(CupriDocument doc)
    {
        _model.AttachDoc(doc); // the Diagnostics page reads live frame/video internals off the doc
        doc.OnClick(".nav", e => { if (e.Element.GetAttribute("data-section") is { } s) _model.Section = s; });
        // Links (<a href>): an internal href routes to that section (like the sidebar); external hrefs are
        // opened in a browser by the host (DesktopHost / the WASM page). #anchors the engine scrolls itself.
        doc.Navigated += e => { if (!e.External && KnownSections.Contains(e.Href)) _model.Section = e.Href; };
        // Burger button and the "CupriFace" wordmark both toggle the sidebar (a selector list —
        // dispatch fires on the innermost matching element, so a burger click can't double-toggle).
        // The toggle means "do the opposite of what I can currently SEE", which below the narrow
        // breakpoint is not the same as "the opposite of the model flag": the sidebar may be an
        // icon rail because of the @media rule while the flag still says expanded. Present() records
        // the logical width each frame, so the handler can tell which of the two states is on screen.
        doc.OnClick(".collapse-btn, .brand-label", _ =>
        {
            var showingRail = _model.Sidebar == "collapsed" || (_model.Sidebar != "expanded" && _logicalWidth <= 760);
            _model.Sidebar = showingRail ? "expanded" : "collapsed";
        });
        // The row itself toggles dark mode, which is the ONLY way to reach it while the sidebar is
        // an icon rail: the switch is display:none there, leaving an icon that did nothing when
        // tapped. Clicking the switch still goes to the switch (dispatch applies the innermost
        // element's behaviour), so this never double-toggles.
        doc.OnClick(".side-toggle", _ => _model.DarkMode = !_model.DarkMode);
        doc.OnClick(".act-submit", _ => _model.FormOk = doc.ValidateAll());
        // The new <cupri-form> validates ITS OWN fields — the Inputs page's half-filled signup box
        // beside it stays quiet, which document-wide ValidateAll could not manage.
        doc.OnClick(".form-submit", _ =>
            _model.FormStatus = doc.Validate("demo") ? "Looks good" : "Check the fields above");
        // …and the same attribute is the submit scope, so Enter in either field submits the form and
        // says which one it was.
        doc.OnSubmit("data-cupri-form", e =>
        {
            _model.FormStatus = doc.Validate(e.Value) ? $"Sent ({e.Value})" : "Check the fields above";
            return true;
        });
        doc.OnClick(".swatch", e => { if (e.Element.GetAttribute("data-accent") is { } a) _model.Accent = a; });
        doc.OnClick(".ctx-act", e => { if (e.Element.GetAttribute("data-action") is { } a) _model.CtxAction = a; });
        void OpenPalette() { _model.PaletteQuery = ""; _model.PaletteOpen = true; }
        doc.OnClick(".search-btn", _ => OpenPalette());                           // open the command palette (button)
        doc.OnShortcut(CupriFace.Interaction.KeyMods.Ctrl, "k", OpenPalette);     // …or Ctrl/Cmd + K

        // ---- Keyboard section ------------------------------------------------------------------
        // Named keys, which only became bindable in v0.10.0 — before that OnShortcut took a string
        // that read as though any key name would do and silently matched single characters only.
        // Ctrl+Enter fires anywhere, including mid-edit, which is what makes it a send key.
        doc.OnShortcut(CupriFace.Interaction.KeyMods.Ctrl, "Enter", () => Send("Ctrl+Enter"));

        // A BARE key only fires when no field is focused, so this cannot eat a keystroke someone is
        // typing. Escape is the exception the engine places by hand: it runs below the built-in
        // dismissals — an open palette or dialog still closes first — and above the plain blur, so
        // it still means "cancel" while the composer has focus.
        doc.OnShortcut(CupriFace.Interaction.KeyMods.None, "Escape", () =>
        {
            if (_model.Section != "keyboard") return;      // the page's own key, not a global one
            _model.Composer = "";
            _model.KeyLog = "Escape — composer cleared";
        });

        // The composer is marked submit-on-enter, so a plain Enter submits and Shift+Enter still
        // starts a new line. The attribute names WHICH field submitted, exactly as OnAction and
        // OnContext name what was clicked.
        doc.OnSubmit("data-composer", e => { Send($"Enter on \"{e.Value}\""); return true; });

        void Send(string how)
        {
            if (_model.Section != "keyboard") return;
            var text = _model.Composer.Trim();
            if (text.Length == 0) { _model.KeyLog = $"{how} — nothing to send"; return; }
            _model.SentCount++;
            _model.Composer = "";
            _model.KeyLog = $"{how} — sent \"{Shorten(text)}\"";
        }

        // Newlines are the point of Shift+Enter, so show them rather than letting the log go quiet.
        static string Shorten(string t) =>
            (t.Length <= 28 ? t : t[..28] + "…").Replace("\n", "⏎ ");

        doc.OnReorder(e =>
        {
            // The kanban columns carry data-col; the standalone Tasks list doesn't. Move the card from the
            // source list to the target (same list for a within-column/list reorder).
            var from = _model.ReorderList(e.List.GetAttribute("data-col"));
            var to = _model.ReorderList(e.ToList.GetAttribute("data-col"));
            if (from is null || to is null || e.From < 0 || e.From >= from.Count) return;
            var card = from[e.From];
            from.RemoveAt(e.From);
            to.Insert(Math.Clamp(e.To, 0, to.Count), card);
        });
        doc.OnClick(".act-dialog", _ => _model.DialogOpen = true);
        doc.OnClick(".act-drawer", _ => _model.DrawerOpen = true);
        doc.OnClick(".act-shelf", _ => _model.ShelfOpen = true);
        doc.OnClick(".act-toast", e =>
        {
            var kind = e.Element.GetAttribute("data-toast-kind") ?? "";
            doc.Toast(kind switch { "success" => "Changes saved", "error" => "Couldn't reach the server", _ => "Heads up — something happened" }, kind);
        });
        doc.OnClick(".act-gc", _ => GC.Collect());
        // Zoom via buttons — a slider would fight the live re-scale it triggers.
        doc.OnClick(".zoom-dec", _ => _model.ZoomPct = Math.Clamp(_model.ZoomPct - 10, 80, 200));
        doc.OnClick(".zoom-inc", _ => _model.ZoomPct = Math.Clamp(_model.ZoomPct + 10, 80, 200));
    }

    private float _logicalWidth = 1024;   // what the sidebar toggle reads to know what's on screen

    public override PresentInfo Present(float w, float h)
    {
        var info = PresentFor(w, h);
        _logicalWidth = info.LogicalWidth;
        return info;
    }

    private PresentInfo PresentFor(float w, float h) => _model.Scaling switch
    {
        "none" => new PresentInfo(Width, Height, 1f),                                  // fixed design size
        "zoom" => Zoomed(w, h, _model.ZoomPct / 100f),                                 // hard DPI-like scale
        "hybrid" => Zoomed(w, h, MathF.Min(w / Width, h / Height)),                    // fit the tighter axis, reflow the other
        _ => new PresentInfo(w, h, 1f),                                                // responsive
    };

    private static PresentInfo Zoomed(float w, float h, float z)
    {
        z = Math.Clamp(z, 0.25f, 4f);
        return new PresentInfo(w / z, h / z, z);
    }
}

[CupriBindable]
public sealed partial class ShowcaseModel
{
    public string Section { get; set; } = "controls";

    public string SecControls => Section == "controls" ? "block" : "none";
    public string SecComponents => Section == "components" ? "block" : "none";
    public string SecCharts => Section == "charts" ? "block" : "none";
    public string SecImages => Section == "images" ? "block" : "none";
    public string Sec3d => Section == "3d" ? "block" : "none";
    public string SecOverlays => Section == "overlays" ? "block" : "none";
    public string SecLayout => Section == "layout" ? "block" : "none";
    public string SecMotion => Section == "motion" ? "block" : "none";
    public string SecStyling => Section == "styling" ? "block" : "none";
    public string SecKeyboard => Section == "keyboard" ? "block" : "none";
    public string SecSettings => Section == "settings" ? "block" : "none";
    public string SecDiag => Section == "diag" ? "block" : "none";
    public string NavControls => Section == "controls" ? "active" : "";
    public string NavComponents => Section == "components" ? "active" : "";
    public string NavCharts => Section == "charts" ? "active" : "";
    public string NavImages => Section == "images" ? "active" : "";
    public string Nav3d => Section == "3d" ? "active" : "";
    public string NavOverlays => Section == "overlays" ? "active" : "";
    public string NavLayout => Section == "layout" ? "active" : "";
    public string NavMotion => Section == "motion" ? "active" : "";
    public string NavStyling => Section == "styling" ? "active" : "";
    public string NavKeyboard => Section == "keyboard" ? "active" : "";
    public string NavSettings => Section == "settings" ? "active" : "";
    public string NavDiag => Section == "diag" ? "active" : "";

    // ---- Components section: the newer controls -----------------------------
    public string Crumb { get; set; } = "march";
    public double PriceFrom { get; set; } = 80;
    public double PriceTo { get; set; } = 340;
    public string Tags { get; set; } = "design,engine";
    public string FormName { get; set; } = "";
    public string FormEmail { get; set; } = "";
    public string FormStatus { get; set; } = "";

    // ---- Keyboard section ---------------------------------------------------
    // Everything below is reachable from the keyboard alone, which is the point of the page: Tab
    // and Shift+Tab walk the controls, and the shortcuts are real registrations rather than a
    // printed list. KeyLog is what makes an invisible interaction visible.
    public string Composer { get; set; } = "";
    public string KeyLog { get; set; } = "nothing yet — try Tab, then Ctrl+Enter";
    public int SentCount { get; set; }
    public string SentLabel => SentCount == 1 ? "1 message sent" : $"{SentCount} messages sent";
    public bool KbNotify { get; set; }
    public string KbPlan { get; set; } = "monthly";

    // 1:1 by default — the window's own pixels, reflowing as it resizes. "hybrid" used to be the
    // default, which scales the whole UI up on a large monitor; that is a demo of the scaling modes,
    // not a sensible starting state for the app. The Settings page still switches between all four.
    public string Scaling { get; set; } = "responsive";
    public int ZoomPct { get; set; } = 100;
    public string ThemeClass => DarkMode ? "dark" : "";

    /// <summary>"" (auto — the @media rule decides), "collapsed" or "expanded". Three states, not
    /// two, because an explicit choice has to be able to override the responsive default in BOTH
    /// directions.</summary>
    public string Sidebar { get; set; } = "";
    public string SidebarClass => Sidebar;                             // width transitions to an icon rail

    // Accent theme (recolors the whole app via the --cupri-accent CSS variable).
    public string Accent { get; set; } = "copper";
    public string AccentTheme => Accent == "copper" ? "" : "theme-" + Accent;
    public string SwCopper => Accent == "copper" ? "on" : "";
    public string SwOcean => Accent == "ocean" ? "on" : "";
    public string SwForest => Accent == "forest" ? "on" : "";
    public string SwGrape => Accent == "grape" ? "on" : "";

    // Last item chosen from the right-click <cupri-context-menu> demo.
    public string CtxAction { get; set; } = "";
    public string CtxActionLabel => CtxAction.Length == 0 ? "Pick an item from the menu…" : "Last action: " + CtxAction;

    // Command palette (opened from the sidebar search button; commands navigate via Section / toggle DarkMode).
    public bool PaletteOpen { get; set; }
    public string PaletteQuery { get; set; } = "";

    public int Volume { get; set; } = 60;
    public string Name { get; set; } = "";
    public string City { get; set; } = "";
    // Validation demo form.
    public string SignupName { get; set; } = "";
    public string SignupEmail { get; set; } = "";
    public string SignupPass { get; set; } = "";
    public bool FormOk { get; set; }
    public string SubmitOk => FormOk ? "inline-flex" : "none"; // flex: check icon + label side by side
    public string Date { get; set; } = "2026-08-15";
    public bool DateOpen { get; set; }
    public string Time { get; set; } = "14:30";
    public bool TimeOpen { get; set; }
    public string BrandColor { get; set; } = "#B87333"; // <cupri-color> demo — the copper accent as hex
    public bool BrandOpen { get; set; }
    public string TableSort { get; set; } = "";
    public string TableSel { get; set; } = ""; // comma-set of selected row indices (multi-select)
    public string TableCols { get; set; } = ""; // per-column widths (px) written by drag-resizing headers
    public string TableSelLabel => TableSel.Split(',', System.StringSplitOptions.RemoveEmptyEntries).Length is var n && n > 0 ? $"{n} selected" : "none selected";
    public string Query { get; set; } = "";
    public string Sales { get; set; } = "12,19,7,15,22,9,14"; // bound into the bar chart on the Charts page
    public string Password { get; set; } = "";
    public bool ShowPassword { get; set; }
    public string ViewMode { get; set; } = "grid";
    public int Rating { get; set; } = 4;
    public int Page { get; set; } = 1;
    public int Quantity { get; set; } = 3;
    public bool Notifications { get; set; } = true;
    public bool DarkMode { get; set; }
    public string Size { get; set; } = "medium";
    public string ImageFit { get; set; } = "contain"; // <cupri-image> object-fit, chosen via radios

    // The video card's size demo: "<size>-<speed>" set by the buttons beside the player. The bound
    // style carries BOTH the target size and a `transition` — the engine's width/height transitions
    // are real layout animations, so the frames, the controls bar and the page all reflow per frame.
    public string VideoMode { get; set; } = "small-fast";
    public string VideoStyle
    {
        get
        {
            // Large is sized to still fit beside the buttons at the default window width — the
            // flex row would otherwise clamp the video and the transition would stop short.
            var (w, h) = VideoMode.StartsWith("large", StringComparison.Ordinal) ? (500, 281) : (320, 180);
            var dur = VideoMode.EndsWith("slow", StringComparison.Ordinal) ? "1.5s" : "0.25s";
            return $"width:{w}px;height:{h}px;border-radius:10px;transition:width {dur} ease, height {dur} ease";
        }
    }
    public bool DialogOpen { get; set; }
    public bool DialogBlur { get; set; } = true;  // frost the page behind the modal (toggle inside it)
    public bool DrawerOpen { get; set; }
    public bool DrawerBlur { get; set; } = true;
    public bool ShelfOpen { get; set; }
    public bool ShelfBlur { get; set; } = true;
    public bool MenuOpen { get; set; }

    // Components section
    public string Tab { get; set; } = "one";
    public bool SizeOpen { get; set; }
    public string Notes { get; set; } = "";
    public bool Acc1 { get; set; } = true;
    public bool Acc2 { get; set; }
    public List<string> Tasks { get; set; } = new() { "Draft the release notes", "Review the layout perf PR", "Reply to the design thread", "Plan next week's sprint" };

    // Kanban board: three columns of cards, dragged within a column or across to another.
    // 2,000-row source for the virtualized list — only the visible window is ever built.
    public List<string> BigList { get; set; } = System.Linq.Enumerable.Range(1, 2000).Select(i => $"Row {i} — some item detail").ToList();

    public List<string> KbTodo { get; set; } = new() { "Design the empty states", "Write the changelog", "Reply to the design thread" };
    public List<string> KbDoing { get; set; } = new() { "Wire the command palette" };
    public List<string> KbDone { get; set; } = new() { "Ship the context menu", "Fix the collapsed sidebar" };
    // Map a reorder list's data-col (null = the standalone Tasks list) to its backing list.
    public List<string>? ReorderList(string? col) => col switch
    {
        null => Tasks, "todo" => KbTodo, "doing" => KbDoing, "done" => KbDone, _ => null,
    };
    public bool TreeOpen { get; set; } = true;
    public bool PopOpen { get; set; }

    // Diagnostics — live metrics. The OS-process metrics (working set, private bytes, threads)
    // are EXPENSIVE (Process.GetCurrentProcess + Threads enumerates every thread) and would run
    // on every data-bind (i.e. every click/keystroke, even when the tab is hidden), so they're
    // sampled at most once per second into a cache. GC/Stopwatch are cheap. On the browser WASM
    // sandbox System.Diagnostics.Process is unsupported → the process metrics show "n/a".
    private static readonly System.Diagnostics.Stopwatch _up = System.Diagnostics.Stopwatch.StartNew();
    private static string Mb(long bytes) => (bytes / (1024.0 * 1024)).ToString("0.0") + " MB";
    private static double _lastSample = -1;
    private static string _ws = "…", _pv = "…", _thr = "…";

    // Rolling RAM history for the live monitor chart on the Diagnostics page — the last minute of samples
    // (1 Hz, driven by the page's per-second refresh) with a fixed, ratcheting ceiling so the baseline
    // doesn't jump as the window scrolls.
    private const int RamWindow = 60;
    private static readonly List<double> _ram = new();
    private static double _ramCeil = 50;

    private static void Sample()
    {
        var now = _up.Elapsed.TotalSeconds;
        if (now - _lastSample < 1.0) return; // cache: at most once per second
        _lastSample = now;
        double ramMb;
        try { using var p = System.Diagnostics.Process.GetCurrentProcess(); _ws = Mb(p.WorkingSet64); _pv = Mb(p.PrivateMemorySize64); _thr = p.Threads.Count.ToString(); ramMb = p.WorkingSet64 / (1024.0 * 1024); }
        catch { _ws = _pv = _thr = "n/a"; ramMb = GC.GetTotalMemory(false) / (1024.0 * 1024); } // browser/WASM: no Process → managed heap

        // Seed a full window on the first sample so the monitor shows a graph straight away (a gentle wave
        // around the current value; it scrolls out as real samples arrive over the next minute).
        if (_ram.Count == 0)
            for (var i = 0; i < RamWindow; i++) _ram.Add(ramMb * (0.9 + 0.08 * System.Math.Sin(i * 0.5)));
        _ram.Add(ramMb);
        while (_ram.Count > RamWindow) _ram.RemoveAt(0);
        _ramCeil = System.Math.Max(_ramCeil, System.Math.Ceiling(ramMb * 1.3 / 25) * 25); // headroom, rounded up, never down
    }
    public string WorkingSetMb { get { Sample(); return _ws; } }
    public string PrivateMb { get { Sample(); return _pv; } }
    public string Threads { get { Sample(); return _thr; } }
    public string ManagedHeapMb => Mb(GC.GetTotalMemory(false));
    public string GcCounts => $"{GC.CollectionCount(0)} / {GC.CollectionCount(1)} / {GC.CollectionCount(2)}";
    public string Uptime => $"{(int)_up.Elapsed.TotalMinutes}m {_up.Elapsed.Seconds:00}s";

    // The rolling RAM monitor: last-minute window, its fixed ceiling, and the latest reading.
    public string RamHistory { get { Sample(); return string.Join(",", _ram.Select(v => v.ToString("0.#", System.Globalization.CultureInfo.InvariantCulture))); } }
    public string RamCeiling { get { Sample(); return _ramCeil.ToString(System.Globalization.CultureInfo.InvariantCulture); } }
    public string RamNow { get { Sample(); return _ram.Count > 0 ? _ram[^1].ToString("0.0") + " MB" : "…"; } }

    // ---- frame-pipeline + video internals (engine-provided; see CupriDocument.LastFrame) --------
    private CupriDocument? _doc;
    internal void AttachDoc(CupriDocument doc) => _doc = doc;

    // ---- 3D section ---------------------------------------------------------
    // The demo's actual claim is that ONE app gets composited two different ways depending on what
    // the host can do, so the page says which way it got. Note what this needs to know about 3D:
    // nothing. It asks the engine's surface registry what kind of surface is registered, which is
    // public API — no reference to a renderer, and no #if per host. A host that wires nothing
    // reports it honestly and the element falls through to its poster.
    private ISurfaceSource? Surface3d => _doc?.Surfaces.Get("showcase3d");

    // Asks what the surface IS, not what it is doing this instant. HostComposited alone is a
    // transient — a producer may report it only once it has pixels (video does, and so does the 3D
    // surface, so the hole is not punched onto a bare page while a GL context comes up) — so a
    // caption bound at rebuild time caught it mid-startup and said "painted" about the browser.
    // UnderlayElement is a declaration and does not move.
    public string Lane3d => Surface3d switch
    {
        null => "not wired on this host — the viewport paints nothing and the panel behind shows",
        { UnderlayElement: not null } or { HostComposited: true } =>
            "host-composited: the engine punches a transparent hole and a WebGL canvas underneath "
            + "shows through it",
        _ => "painted: the renderer hands the engine finished frames, drawn into the display list "
             + "like any other image",
    };

    /// <summary>Shown beside the viewport so the page never claims 3D it has not got.</summary>
    public string Has3d => Surface3d is null ? "none" : "block";
    public string No3d => Surface3d is null ? "block" : "none";

    public string FrameBuild
    {
        get
        {
            if (_doc is null) return "…";
            var f = _doc.LastFrame;
            return $"{f.LayoutMs:0.00} / {f.PaintListMs:0.00} / {f.DiffMs:0.00} ms";
        }
    }
    public string FrameRaster
    {
        get
        {
            if (_doc is null) return "…";
            var f = _doc.LastFrame;
            return f.DamagePixels > 0 ? $"{f.RasterMs:0.00} ms · {f.DamagePixels / 1000} kpx" : "clean";
        }
    }
    public string VideoDiag => _doc?.VideoDiagnostics ?? "no open players";
}
