using System.Text;
using Microsoft.CodeAnalysis;

namespace CupriFace.Resources.Gen;

/// <summary>
/// Emits a strongly-typed <c>Assets</c> class from the project's embedded asset files, so markup /
/// style / media resources are referenced with compile-time safety instead of magic strings.
///
/// Input: the build (<c>CupriFace.Resources.targets</c>) marks each <c>Assets/**</c> file as an
/// <c>AdditionalFiles</c> item carrying its stable manifest name in <c>CupriLogicalName</c> metadata.
/// This generator turns each into a member returning a <c>CupriFace.Resources.CupriSource.Embedded(…)</c>.
///
/// <code>
/// Assets.ShowcaseApp.Html   // ← "Assets/ShowcaseApp.html"
/// Assets.ShowcaseApp.Css    // ← "Assets/ShowcaseApp.css"
/// </code>
/// Renaming or deleting the file removes the member, so stale references fail the build.
/// </summary>
[Generator]
public sealed class AssetsGenerator : IIncrementalGenerator
{
    private const string LogicalNameKey = "build_metadata.AdditionalFiles.CupriLogicalName";
    private const string RootNamespaceKey = "build_property.RootNamespace";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Each asset → (logicalName, fileName) using the per-file CupriLogicalName metadata.
        var assets = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, _) =>
            {
                var (text, provider) = pair;
                provider.GetOptions(text).TryGetValue(LogicalNameKey, out var logical);
                return logical is { Length: > 0 } ? new Asset(logical!) : null;
            })
            .Where(static a => a is not null)
            .Collect();

        var rootNs = context.AnalyzerConfigOptionsProvider.Select(static (p, _) =>
            p.GlobalOptions.TryGetValue(RootNamespaceKey, out var ns) && ns.Length > 0 ? ns : null);

        context.RegisterSourceOutput(assets.Combine(rootNs),
            static (spc, data) => Emit(spc, data.Left!, data.Right));
    }

    private sealed class Asset
    {
        public Asset(string logicalName) => LogicalName = logicalName;
        public string LogicalName { get; }
        // "Assets/ShowcaseApp.html" → group "ShowcaseApp", member "Html".
        public string Group => Identifier(Path.GetFileNameWithoutExtension(LogicalName));
        public string Member => Pascal(Path.GetExtension(LogicalName).TrimStart('.'));
    }

    private static void Emit(SourceProductionContext spc, IReadOnlyList<Asset?> assets, string? rootNs)
    {
        if (assets.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (rootNs is not null) sb.AppendLine($"namespace {rootNs};").AppendLine();

        sb.AppendLine("/// <summary>Compile-time-safe accessors for this project's embedded assets.</summary>");
        sb.AppendLine("public static partial class Assets");
        sb.AppendLine("{");

        foreach (var group in assets.Where(a => a is not null)!
                     .GroupBy(a => a!.Group).OrderBy(g => g.Key))
        {
            sb.AppendLine($"    public static class {group.Key}");
            sb.AppendLine("    {");
            foreach (var asset in group.GroupBy(a => a!.Member).Select(g => g.First()).OrderBy(a => a!.Member))
                sb.AppendLine(
                    $"        public static global::CupriFace.Resources.CupriSource {asset!.Member} => " +
                    $"global::CupriFace.Resources.CupriSource.Embedded(typeof(Assets).Assembly, \"{asset.LogicalName}\");");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        spc.AddSource("Assets.g.cs", sb.ToString());
    }

    // A safe C# identifier: non-alphanumerics → '_', prefix if it starts with a digit.
    private static string Identifier(string raw)
    {
        var chars = raw.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        var s = new string(chars);
        return s.Length == 0 || char.IsDigit(s[0]) ? "_" + s : s;
    }

    private static string Pascal(string ext) =>
        ext.Length == 0 ? "Source" : char.ToUpperInvariant(ext[0]) + ext.Substring(1).ToLowerInvariant();
}
