using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CupriFace.Binding.Gen;

/// <summary>
/// Emits an <c>IBindableAccessor</c> implementation for every partial type marked
/// <c>[CupriBindable]</c>, giving reflection-free property lookup for the binding
/// engine (DESIGN.md §6 — AOT/trim-clean).
/// </summary>
[Generator]
public sealed class BindableGenerator : IIncrementalGenerator
{
    private const string AttributeName = "CupriFace.Binding.CupriBindableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(types, static (spc, symbol) => Emit(spc, symbol));
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var keyword = type.TypeKind == TypeKind.Struct ? "struct" : "class";

        // Public instance readable properties.
        var props = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && !p.IsWriteOnly && p.Parameters.IsEmpty)
            .Select(p => p.Name)
            .Distinct();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null) sb.AppendLine($"namespace {ns};").AppendLine();

        sb.AppendLine($"partial {keyword} {type.Name} : global::CupriFace.Binding.IBindableAccessor");
        sb.AppendLine("{");
        sb.AppendLine("    public object? GetBindable(string name) => name switch");
        sb.AppendLine("    {");
        foreach (var name in props)
            sb.AppendLine($"        \"{name}\" => this.{name},");
        sb.AppendLine("        _ => null,");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        spc.AddSource($"{type.Name}.Bindable.g.cs", sb.ToString());
    }
}
